### ISSUE TITLE
[Python] How to save a NO_TIME field to a med file?

### ISSUE THREAD

**Issue by Iceman9** [SalomePlatform/medcoupling#3]
What is the correct way of storing a field, that is a constant really, to a MED file.

I tried using the NO_TIME identifier when creating a field but I get a InterpKernelException saying that no time info is attached to such field... but the field has no time info.

Do I have to create a CONST_ON_TIME_INTERVAL field? If so, could this be shown in the documentation? 

Sometimes I have quantities that take unnecessary time to calculate but are constant in nature so I prefer to calculate them only once per mesh and store it. It's faster to read it than to calculate it every time.

**Comment by asonolet** [comment]
Hello @Iceman9 ,

You can find examples of reading/writing fields in the following repo: https://github.com/cea-trust-platform/MEDCoupling_tutos/tree/master/tutorials/ExempleThematique under the 3rd and 4th folders.
Usually when a field is constant over time, it is declared as `mc.ONE_TIME`.

I hope it answers your question !

**Comment by Iceman9** [comment]
That is one solution, yes. I have maybe tackled this impractically by focusing only on NO_TIME property.

But for instance, if I save a field, which is constant, as mc.ONE_TIME, I have to be mindful by providing the time information when reading the field. It would be nice just to say readConstantField by providing the name of the field and mesh :).

However, thanks, this is still a solution regarding saving the data in the MED file for which we only want to save one instance of the quantity.

**Comment by Iceman9** [comment]
That is one solution, yes. I have maybe tackled this impractically by focusing only on NO_TIME property.

But for instance, if I save a field, which is constant, as mc.ONE_TIME, I have to be mindful by providing the time information when reading the field. It would be nice just to say readConstantField by providing the name of the field and mesh :).

However, thanks, this is still a solution regarding saving the data in the MED file for which we only want to save one instance of the quantity.
